spring.datasource.url=jdbc:mysql://localhost:3306/grading_system
spring.datasource.username=root
spring.datasource.password=Bivon@016

spring.jpa.show-sql=false

server.port=8080

app.frontend-url=https://schoolgrading.duckdns.org